- repo: https://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-vet
    - id: golangci-lint
    - id: go-critic
    - id: go-unit-tests
    - id: go-build
    # - id: go-mod-tidy