basePath: /
definitions:
  errors.DefaultError:
    properties:
      message:
        type: string
    type: object
  errors.ValidationError:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  models.Client:
    properties:
      email:
        maxLength: 125
        type: string
      id:
        type: integer
      name:
        maxLength: 127
        minLength: 3
        type: string
      surname:
        maxLength: 255
        minLength: 3
        type: string
    required:
    - email
    - name
    - surname
    type: object
host: localhost:8080
info:
  contact: {}
  description: Client registration service that enable to manage clients and their
    addresses, contacts and documents.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://posteris.io/terms/
  title: Client Registration service
  version: "1.0"
paths:
  /api/v1/clientes:
    post:
      consumes:
      - application/json
      description: Create a new client and persist it at the database.
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Client'
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/errors.ValidationError'
            type: array
        "415":
          description: Unsupported Media Type
          schema:
            $ref: '#/definitions/errors.DefaultError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.DefaultError'
      summary: Create new Client
      tags:
      - Client
  /api/v1/clientes/{id}:
    get:
      consumes:
      - application/json
      description: Perform a paginated search through the client repository geting
        all active users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Client'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.DefaultError'
      summary: List all clients
      tags:
      - Client
swagger: "2.0"
