basePath: /
definitions:
  fiber.Map:
    additionalProperties: true
    type: object
  models.Client:
    properties:
      email:
        type: string
      name:
        maxLength: 127
        minLength: 2
        type: string
      surname:
        maxLength: 255
        minLength: 2
        type: string
      uuid:
        type: string
    required:
    - email
    - name
    - surname
    type: object
  validate.CustomError:
    properties:
      field:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Client Registration service
  version: "1.0"
paths:
  /api/v1/clientes:
    post:
      consumes:
      - application/json
      description: Create a new client and persist it at the database. This action
        can be done by sync and async way. By default, the sync is selected, but,
        when the parameter async is set as true, the system will assume that the implementation
        will perform the request asynchronously, and the requester should wait by
        the response at a callback URL.
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Client'
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/validate.CustomError'
            type: array
        "415":
          description: Unsupported Media Type
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Create new Client
      tags:
      - Client
  /api/v1/clientes/{id}:
    get:
      consumes:
      - application/json
      description: Perform a paginated search through the client repository geting
        all active users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Client'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: List all clients
      tags:
      - Client
swagger: "2.0"
